### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by shahinur-alam** [MandyMo/HIU-DMTL#1]
Hi,
Thank you very much for uploading the source code. Would you please specify the required package lists?

In my case, I only see a white area in the output.

![Screenshot_1](https://user-images.githubusercontent.com/5467074/140039249-94634aed-71ce-4fbe-afff-acbc08de547e.png)

**Comment by MandyMo** [comment]
> Hi, Thank you very much for uploading the source code. Would you please specify the required package lists?
> 
> In my case, I only see a white area in the output.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/5467074/140039249-94634aed-71ce-4fbe-afff-acbc08de547e.png)

Thank you for your attention about our work. 
The hand_detection folder only contains code of hand detection which will be used for hand reconstruction.
Regarding the code and the dataset of hand reconstruction, it will be released latter (maybe afeter the cvpr 2022 deadline).

**Comment by shahinur-alam** [comment]
Thank you very much for your reply.

I will be waiting for this.

By the way, all the best for CVPR 2022. :)

**Comment by CODE-SUBMIT** [comment]
the cvpr2022 review deadline is coming, could you please open the reconstruction code.
