### ISSUE TITLE
when will the data be released

### ISSUE THREAD

**Issue by zjhthu** [MandyMo/HIU-DMTL#2]
Hi, thanks for the great work. And when will the data be released?

**Comment by MandyMo** [comment]
please remember to call me after the cvpr2022 deadline (Nov. 23) .

**Comment by josh-zhu** [comment]
Really nice work, hope for the release

**Comment by mrchen229** [comment]
Really nice work, hope for the release too.

**Comment by MandyMo** [comment]
The dataset has been released, please drop a email to 1025679612 at qq dot com to obtain the well-defined dataset.
