### ISSUE TITLE
dataset json means?

### ISSUE THREAD

**Issue by LumenForgeX** [MandyMo/HIU-DMTL#3]
Could you explain this json?

pts2d_2hand、 pts3d_w_2hand、hand_type、hand_type_valid

Thanks!

**Comment by MandyMo** [comment]
The pts2d_2hand comprises the keypoints' position of the two hands (right hand and left hand), the hand_type indicates if the corresponding hand exists in the image, and the hand_type_valid indicates if the hand_type annotation is valid.

**Comment by LumenForgeX** [comment]
Thanks! ☺
